/**
 * Student Model - Represents a student entity
 * Mirrors the backend Student model
 */
export interface Student {
  stdid: number;
  stdname: string;
  mobileno?: string;
  email?: string;
  city?: string;
  state?: string;
  pincode?: string;
  address1?: string;
  address2?: string;
}

/**
 * CreateStudent DTO - Used for creating/updating students
 * Doesn't include stdid as it's generated by the database
 */
export interface CreateStudentDto {
  stdname: string;
  mobileno?: string;
  email?: string;
  city?: string;
  state?: string;
  pincode?: string;
  address1?: string;
  address2?: string;
}
